site_name: China Rock Lyrics
site_url: https://chinarocklyrics.github.io/
theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.indexes

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; 2025 chinarocklyrics@gmail.com. Distributed by an <a href="https://github.com/chinarocklyrics/chinarocklyrics.github.io/blob/main/LICENSE.txt">BSD-3 license.</a>
extra:
  generator: false
  analytics:
    provider: google
    property: G-H778WWH39N
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=61574273391141
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ChinaRockLyrics

# Page tree
nav:
  - Home: index.md
  - Singer or Band Name:
      - singer_or_band_name/index.md
      - Singer or Band Name Starts with A:
          - singer_or_band_name/singer_or_band_name_a/index.md
          - ADO: singer_or_band_name/singer_or_band_name_a/ADO/index.md
      - Singer or Band Name Starts with C:
          - singer_or_band_name/singer_or_band_name_c/index.md
          - 崔健: singer_or_band_name/singer_or_band_name_c/Cui_Jian/index.md
      - Singer or Band Name Starts with H:
          - singer_or_band_name/singer_or_band_name_h/index.md
          - 黑豹: singer_or_band_name/singer_or_band_name_h/Hei_Bao/index.md
          - 侯牧人: singer_or_band_name/singer_or_band_name_h/Hou_Mu_Ren/index.md
          - 红色部队: singer_or_band_name/singer_or_band_name_h/Hong_Se_Bu_Dui/index.md
      - Singer or Band Name Starts with M:
          - singer_or_band_name/singer_or_band_name_m/index.md
          - 面孔: singer_or_band_name/singer_or_band_name_m/Mian_Kong/index.md    
      - Singer or Band Name Starts with T:
          - singer_or_band_name/singer_or_band_name_t/index.md
          - 唐朝: singer_or_band_name/singer_or_band_name_t/Tang_Chao/index.md
      - Singer or Band Name Starts with W:
          - singer_or_band_name/singer_or_band_name_w/index.md
          - 蔚华: singer_or_band_name/singer_or_band_name_w/Wei_Hua/index.md
      - Singer or Band Name Starts with Y:
          - singer_or_band_name/singer_or_band_name_y/index.md
          - 眼镜蛇: singer_or_band_name/singer_or_band_name_y/Yan_Jing_She/index.md
      - Singer or Band Name Starts with Z:
          - singer_or_band_name/singer_or_band_name_z/index.md
          - 赵牧阳: singer_or_band_name/singer_or_band_name_z/Zhao_Mu_Yang/index.md
          - 张楚: singer_or_band_name/singer_or_band_name_z/Zhang_Chu/index.md
          - 赵刚: singer_or_band_name/singer_or_band_name_z/Zhao_Gang/index.md
          - 自我教育: singer_or_band_name/singer_or_band_name_z/Zi_Wo_Jiao_Yu/index.md
          - 臧天朔: singer_or_band_name/singer_or_band_name_z/Zang_Tian_Shuo/index.md
          - 做梦: singer_or_band_name/singer_or_band_name_z/Zuo_Meng/index.md
  - Song Name:
      - song_name/index.md
      - Song Name Starts with A: song_name/song_name_a/index.md
      - Song Name Starts with B: song_name/song_name_b/index.md
      - Song Name Starts with C: song_name/song_name_c/index.md
      - Song Name Starts with D: song_name/song_name_d/index.md
      - Song Name Starts with F: song_name/song_name_f/index.md
      - Song Name Starts with G: song_name/song_name_g/index.md
      - Song Name Starts with H: song_name/song_name_h/index.md
      - Song Name Starts with J: song_name/song_name_j/index.md
      - Song Name Starts with K: song_name/song_name_k/index.md
      - Song Name Starts with L: song_name/song_name_l/index.md
      - Song Name Starts with M: song_name/song_name_m/index.md
      - Song Name Starts with P: song_name/song_name_p/index.md
      - Song Name Starts with R: song_name/song_name_r/index.md
      - Song Name Starts with S: song_name/song_name_s/index.md
      - Song Name Starts with T: song_name/song_name_t/index.md
      - Song Name Starts with W: song_name/song_name_w/index.md
      - Song Name Starts with X: song_name/song_name_x/index.md
      - Song Name Starts with Y: song_name/song_name_y/index.md
      - Song Name Starts with Z: song_name/song_name_z/index.md
