site_name: China Rock Lyrics
site_url: https://chinarocklyrics.github.io/
theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans
  logo: assets/favicon.ico
  favicon: assets/favicon.ico

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; 2025 chinarocklyrics@gmail.com. Distributed by an <a href="https://github.com/chinarocklyrics/chinarocklyrics.github.io/blob/main/LICENSE.txt">BSD-3 license.</a>
extra:
  generator: false

# Page tree
nav:
  - Home: index.md
  - Singer or Band Name:
#      - singer_or_band_name/index.md
      - Singer or Band Name Starts with C:
#          - singer_or_band_name/singer_or_band_name_c/index.md
          - 崔健: singer_or_band_name/singer_or_band_name_c/Cui_Jian/index.md
      - Singer or Band Name Starts with H:
          - 黑豹: singer_or_band_name/singer_or_band_name_h/Hei_Bao/index.md
      - Singer or Band Name Starts with T:
          - 唐朝: singer_or_band_name/singer_or_band_name_t/Tang_Chao/index.md
  - Song Name:
#      - song_name/index.md
      - Song Name Starts with B: song_name/song_name_b/index.md
      - Song Name Starts with C: song_name/song_name_c/index.md
      - Song Name Starts with D: song_name/song_name_d/index.md
      - Song Name Starts with F: song_name/song_name_f/index.md
      - Song Name Starts with H: song_name/song_name_h/index.md
      - Song Name Starts with J: song_name/song_name_j/index.md
      - Song Name Starts with K: song_name/song_name_k/index.md
      - Song Name Starts with L: song_name/song_name_l/index.md
      - Song Name Starts with M: song_name/song_name_m/index.md
      - Song Name Starts with P: song_name/song_name_p/index.md
      - Song Name Starts with R: song_name/song_name_r/index.md
      - Song Name Starts with S: song_name/song_name_s/index.md
      - Song Name Starts with T: song_name/song_name_t/index.md
      - Song Name Starts with W: song_name/song_name_w/index.md
      - Song Name Starts with X: song_name/song_name_x/index.md
      - Song Name Starts with Y: song_name/song_name_y/index.md
